/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'JC' at '3/30/18 11:29 PM' with Gradle 2.12
 *
 * @author JC, @date 3/30/18 11:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
